const iconsPeople = [
  {
    codes: "1F600",
    char: "😀",
    name: "grinning face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F603",
    char: "😃",
    name: "grinning face with big eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F604",
    char: "😄",
    name: "grinning face with smiling eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F601",
    char: "😁",
    name: "beaming face with smiling eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F606",
    char: "😆",
    name: "grinning squinting face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F605",
    char: "😅",
    name: "grinning face with sweat",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F923",
    char: "🤣",
    name: "rolling on the floor laughing",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F602",
    char: "😂",
    name: "face with tears of joy",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F642",
    char: "🙂",
    name: "slightly smiling face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F643",
    char: "🙃",
    name: "upside-down face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F609",
    char: "😉",
    name: "winking face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F60A",
    char: "😊",
    name: "smiling face with smiling eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F607",
    char: "😇",
    name: "smiling face with halo",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    codes: "1F970",
    char: "🥰",
    name: "smiling face with hearts",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F60D",
    char: "😍",
    name: "smiling face with heart-eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F929",
    char: "🤩",
    name: "star-struck",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F618",
    char: "😘",
    name: "face blowing a kiss",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F617",
    char: "😗",
    name: "kissing face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F61A",
    char: "😚",
    name: "kissing face with closed eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F619",
    char: "😙",
    name: "kissing face with smiling eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    codes: "1F60B",
    char: "😋",
    name: "face savoring food",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F61B",
    char: "😛",
    name: "face with tongue",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F61C",
    char: "😜",
    name: "winking face with tongue",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F92A",
    char: "🤪",
    name: "zany face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F61D",
    char: "😝",
    name: "squinting face with tongue",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F911",
    char: "🤑",
    name: "money-mouth face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    codes: "1F917",
    char: "🤗",
    name: "hugging face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    codes: "1F92D",
    char: "🤭",
    name: "face with hand over mouth",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    codes: "1F92B",
    char: "🤫",
    name: "shushing face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    codes: "1F914",
    char: "🤔",
    name: "thinking face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    codes: "1F910",
    char: "🤐",
    name: "zipper-mouth face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F928",
    char: "🤨",
    name: "face with raised eyebrow",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F610",
    char: "😐",
    name: "neutral face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F611",
    char: "😑",
    name: "expressionless face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F636",
    char: "😶",
    name: "face without mouth",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F636 200D 1F32B FE0F",
    char: "😶‍",
    name: "face in clouds",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F636 200D 1F32B",
    char: "😶‍",
    name: "face in clouds",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F60F",
    char: "😏",
    name: "smirking face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F612",
    char: "😒",
    name: "unamused face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F644",
    char: "🙄",
    name: "face with rolling eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F62C",
    char: "😬",
    name: "grimacing face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F62E 200D 1F4A8",
    char: "😮‍",
    name: "face exhaling",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F925",
    char: "🤥",
    name: "lying face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    codes: "1F60C",
    char: "😌",
    name: "relieved face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
  {
    codes: "1F614",
    char: "😔",
    name: "pensive face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
  {
    codes: "1F62A",
    char: "😪",
    name: "sleepy face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
  {
    codes: "1F924",
    char: "🤤",
    name: "drooling face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
  {
    codes: "1F634",
    char: "😴",
    name: "sleeping face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
  {
    codes: "1F637",
    char: "😷",
    name: "face with medical mask",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F912",
    char: "🤒",
    name: "face with thermometer",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F915",
    char: "🤕",
    name: "face with head-bandage",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F922",
    char: "🤢",
    name: "nauseated face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F92E",
    char: "🤮",
    name: "face vomiting",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F927",
    char: "🤧",
    name: "sneezing face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F975",
    char: "🥵",
    name: "hot face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F976",
    char: "🥶",
    name: "cold face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F974",
    char: "🥴",
    name: "woozy face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F635",
    char: "😵",
    name: "knocked-out face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F635 200D 1F4AB",
    char: "😵‍",
    name: "face with spiral eyes",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F92F",
    char: "🤯",
    name: "exploding head",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-unwell",
  },
  {
    codes: "1F920",
    char: "🤠",
    name: "cowboy hat face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-hat",
  },
  {
    codes: "1F973",
    char: "🥳",
    name: "partying face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-hat",
  },
  {
    codes: "1F60E",
    char: "😎",
    name: "smiling face with sunglasses",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-glasses",
  },
  {
    codes: "1F913",
    char: "🤓",
    name: "nerd face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-glasses",
  },
  {
    codes: "1F9D0",
    char: "🧐",
    name: "face with monocle",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-glasses",
  },
  {
    codes: "1F615",
    char: "😕",
    name: "confused face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F61F",
    char: "😟",
    name: "worried face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F641",
    char: "🙁",
    name: "slightly frowning face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "2639 FE0F",
    char: "☹️",
    name: "frowning face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F62E",
    char: "😮",
    name: "face with open mouth",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F62F",
    char: "😯",
    name: "hushed face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F632",
    char: "😲",
    name: "astonished face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F633",
    char: "😳",
    name: "flushed face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F97A",
    char: "🥺",
    name: "pleading face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F626",
    char: "😦",
    name: "frowning face with open mouth",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F627",
    char: "😧",
    name: "anguished face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F628",
    char: "😨",
    name: "fearful face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F630",
    char: "😰",
    name: "anxious face with sweat",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F625",
    char: "😥",
    name: "sad but relieved face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F622",
    char: "😢",
    name: "crying face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F62D",
    char: "😭",
    name: "loudly crying face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F631",
    char: "😱",
    name: "face screaming in fear",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F616",
    char: "😖",
    name: "confounded face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F623",
    char: "😣",
    name: "persevering face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F61E",
    char: "😞",
    name: "disappointed face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F613",
    char: "😓",
    name: "downcast face with sweat",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F629",
    char: "😩",
    name: "weary face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F62B",
    char: "😫",
    name: "tired face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F971",
    char: "🥱",
    name: "yawning face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-concerned",
  },
  {
    codes: "1F624",
    char: "😤",
    name: "face with steam from nose",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
  {
    codes: "1F621",
    char: "😡",
    name: "pouting face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
  {
    codes: "1F620",
    char: "😠",
    name: "angry face",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
  {
    codes: "1F92C",
    char: "🤬",
    name: "face with symbols on mouth",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
  {
    codes: "1F608",
    char: "😈",
    name: "smiling face with horns",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
  {
    codes: "1F47F",
    char: "👿",
    name: "angry face with horns",
    category: "People",
    group: "Smileys & Emotion",
    subgroup: "face-negative",
  },
];
export default iconsPeople;
